#!/usr/bin/env bash
# sync-canon.sh — refresh v2/canon/ from the game repo.
#
# WHY THIS EXISTS
#   Some v2 material is CANONICAL IN THE GAME REPO because tooling there consumes it:
#   scripts/validate_seeds.py validates data/mythology/entities.jsonl, and
#   scripts/generate_patron_roster.py generates data/patron_roster.json FROM it.
#   Moving those files would break both scripts.
#
#   But a GM running v2 at a table — and a reviewer handed this repo — needs them.
#   So v2/canon/ holds a PROVENANCE-STAMPED SNAPSHOT, regenerated by this script.
#   It is a derived artifact, never a second master. If canon/ and the game repo
#   disagree, THE GAME REPO IS RIGHT — re-run this script.
#
# USAGE
#   ./v2/sync-canon.sh [path-to-game-repo]        (default: ../Galactic-Prime-Time-Game)
set -euo pipefail

GAME="${1:-$(cd "$(dirname "$0")/../.." && pwd)/Galactic-Prime-Time-Game}"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/canon"

[ -d "$GAME" ] || { echo "game repo not found: $GAME" >&2; exit 1; }

SHA="$(git -C "$GAME" rev-parse --short HEAD)"
WHEN="$(git -C "$GAME" log -1 --format=%cI)"
DIRTY=""; git -C "$GAME" diff --quiet 2>/dev/null || DIRTY="  ⚠️ SOURCE REPO HAD UNCOMMITTED CHANGES"

mkdir -p "$OUT"
echo "syncing from $GAME @ $SHA"

stamp() { # $1=src-rel $2=dest-name
  local src="$GAME/$1" dst="$OUT/$2"
  [ -f "$src" ] || { echo "  MISSING: $1" >&2; return 0; }
  {
    echo "<!-- GENERATED SNAPSHOT — DO NOT EDIT HERE."
    echo "     Source of truth: Galactic-Prime-Time-Game/$1"
    echo "     Synced from commit $SHA ($WHEN)$DIRTY"
    echo "     Refresh: ./v2/sync-canon.sh -->"
    echo
    cat "$src"
  } > "$dst"
  echo "  ✓ $2"
}

# --- Setting canon: what v2 IS ---
stamp docs/cosmic-casino-canon.md          cosmic-casino-canon.md
stamp docs/setting-rebrand-options.md      setting-rebrand-options.md
stamp docs/DIRECTION.md                    DIRECTION.md
stamp docs/story-canon.md                  story-canon.md
stamp docs/narrative/narrative-design.md   narrative-design.md
stamp docs/ttrpg-update-plan.md            ttrpg-update-plan.md

# --- The patron / divinity system ---
stamp docs/design/patron-gods.md           patron-gods.md
stamp docs/design/mythology-research-spec.md mythology-research-spec.md

# --- Digital rulings (the sim implements these; many port to the table) ---
stamp docs/rules-addendum.md               rules-addendum.md
stamp docs/rules-questionnaire.md          rules-questionnaire.md

# --- Readable cast references, generated from the machine data ---
python3 - "$GAME" "$OUT" "$SHA" "$WHEN" <<'PY'
import json, sys, pathlib
game, out, sha, when = sys.argv[1], pathlib.Path(sys.argv[2]), sys.argv[3], sys.argv[4]
hdr = (f"<!-- GENERATED — DO NOT EDIT HERE.\n"
       f"     Source of truth: Galactic-Prime-Time-Game/data/mythology/entities.jsonl\n"
       f"     Synced from commit {sha} ({when})\n"
       f"     Refresh: ./v2/sync-canon.sh -->\n\n")

ents = []
p = pathlib.Path(game) / "data" / "mythology" / "entities.jsonl"
if p.is_file():
    for line in p.open():
        if line.strip():
            ents.append(json.loads(line))

def row(e):
    n = e["names"]["primary"]
    dom = ", ".join(e.get("domains", []))
    roles = ", ".join(e.get("casino_roles", []))
    return (f"| **{n}** | {e.get('tradition','')} | {dom} | inf {e.get('influence')} / "
            f"rec {e.get('recognition')} | {e.get('depiction_risk')} | {roles} |")

HEAD = ("| Name | Tradition | Domains | Influence / Recognition | Depiction | Casino roles |\n"
        "|---|---|---|---|---|---|\n")

# The 72 goetic demon gods
g = [e for e in ents if e.get("pantheon") == "goetia"]
(out / "goetia-cast.md").write_text(
    hdr + f"# The Ars Goetia — {len(g)} demon gods\n\n"
    "Demons are a **race** (NPCs and enemies, never playable unless a character is changed\n"
    "into one) who **revere demon gods** — these 72. Authored from the Lesser Key of\n"
    "Solomon (public domain), each carrying its real rank, legion count, described form\n"
    "and described powers, mapped onto the casino register.\n\n"
    "**Command is not reverence** (Q-59): a legion bound by force is not a congregation,\n"
    "which is why every goetic spirit sits at influence 1 despite commanding legions.\n"
    "They are powerful and poor — which is exactly why they are at a casino.\n\n"
    + HEAD + "\n".join(row(e) for e in sorted(g, key=lambda x: x["names"]["primary"])) + "\n")

# Everything else
o = [e for e in ents if e.get("pantheon") != "goetia"]
(out / "mythology-cast.md").write_text(
    hdr + f"# Mythology cast — {len(o)} entities ({len(ents)} total with the Goetia)\n\n"
    "The wider corpus the patron roster is drawn from. `depiction_risk: living` marks\n"
    "figures of living religions — handle per the depiction policy.\n\n"
    + HEAD + "\n".join(row(e) for e in sorted(o, key=lambda x: (x.get("tradition",""), x["names"]["primary"]))) + "\n")

# The 24-god MVP patron roster
r = pathlib.Path(game) / "data" / "patron_roster.json"
if r.is_file():
    d = json.loads(r.read_text())
    roster = d.get("roster", d if isinstance(d, list) else [])
    by = {e["id"]: e for e in ents}
    lines = []
    for x in roster:
        i = x.get("id") or x.get("entity_id")
        e = by.get(i)
        lines.append(row(e) if e else f"| `{i}` | — | — | — | — | (not in entities.jsonl) |")
    (out / "patron-roster.md").write_text(
        hdr + f"# The patron roster — {len(roster)} gods\n\n"
        "The MVP set of gods who wager on contestants. Generated in the game repo by\n"
        "`scripts/generate_patron_roster.py` from the corpus; numbers in the source JSON\n"
        "are R14 PLACEHOLDERS awaiting tuning.\n\n" + HEAD + "\n".join(lines) + "\n")
print(f"  ✓ goetia-cast.md ({len(g)}) · mythology-cast.md ({len(o)}) · patron-roster.md")
PY

echo "done — v2/canon/ refreshed from $SHA"
