/**
 * Seeds enemies from a batch module into the enemies collection.
 *
 * DRY RUN by default: prints every create/diff it would make.
 *   node seed-enemies.js                    → dry run (Floor 1 roster)
 *   node seed-enemies.js --apply            → create missing enemies
 *   node seed-enemies.js --apply --force    → also overwrite existing ones
 *                                             whose seed-managed fields differ
 *   node seed-enemies.js --file ./seeds/enemies-f2.js          → another batch
 *   node seed-enemies.js --check            → doctrine check only, no DB
 *
 * Matching is by name, case-insensitive. Existing enemies are NEVER touched
 * without --force (owner edits win). Runbook: backup-db.js → dry run → --apply.
 *
 * RENAMES. Because matching is by name, renaming an entry would orphan its Atlas
 * document and create a second one. A seed may therefore carry
 *   renamedFrom: 'Old Name'
 * and the seeder will find the old document and RENAME IT IN PLACE, keeping its _id
 * and any owner edits. The key is bookkeeping only — it is stripped before the
 * document is written, and `renameProblems()` refuses a rename that would have two
 * seeds claiming one document. Drop the key once the rename has been applied.
 *
 * Before touching the DB this refuses to run unless every entry matches the
 * §21.2 part-budget doctrine for its rank (rulebook/f1-enemy-pass.md E-0.1/E-0.2):
 * a wrong number is a content bug, and it should never reach the campaign DB.
 */
const path = require('path');
// dotenv/mongoose are required lazily, inside run(), so that --check works on a
// bare checkout with no node_modules: the doctrine gate is pure content math.

const apply     = process.argv.includes('--apply');
const force     = process.argv.includes('--force');
const checkOnly = process.argv.includes('--check');
const fileIdx   = process.argv.indexOf('--file');
const seedFile  = fileIdx !== -1 ? process.argv[fileIdx + 1] : './seeds/enemies-f1.js';

// §21.2 part budgets, in FORCE (§7.3). One Force is one basic punch.
//
// ⚡ REWRITTEN 2026-09-01. This used to double per floor (5/10/20/…/1280), which
// rode the withdrawn ×2 material band (L-23). It now tracks the CALIBRATION:
// a mob is worth the AVERAGE contestant's Force for its floor, so that a mob is
// one swing on every floor — "one shot at an average rate of success, or slightly
// below it." A contestant gains about +1 Force per floor, so the mob does too.
//
// --floor is now meaningful for every roster: an F2 roster checks against 6, an
// F3 roster against 7. It is no longer a no-op you can leave alone.
const FLOOR_MOB_HP = { 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 12, 9: 13 };
const RANK_RATIO   = { mob: 1, elite: 12, boss: 25, legendary: 60 };

// ONLY MOBS ARE EXACT. Owner ruling 2026-08-18: "the only one we can decisively say
// always dies in one meaningful shot is mobs" — elites and above should DIFFER from
// one another, so §21.2's ratios are a centre with a tolerance band, not a law.
// The gate exists to catch gross errors, not to flatten the roster.
const TOLERANCE = { elite: [0.5, 2.0], boss: [0.5, 2.0], legendary: [0.5, 2.0] };
// §7.1 — every combatant has a size, and §13 reads it for grapple legality.
const SIZES = ['Small', 'Medium', 'Large', 'Huge'];

// enemy-scaling S-1 — the SIGNATURE HIT per floor, in band units. Unlike HP (which
// is floor-invariant), damage MOVES, because it tracks the contestant's growing body.
// Generated by floor-bands.js; regenerate rather than hand-editing.
const FLOOR_DAMAGE = {
  1: { mob: 4,  elite: 6,  boss: 8,  legendary: 12 },
  2: { mob: 5,  elite: 8,  boss: 10, legendary: 15 },
  3: { mob: 6,  elite: 9,  boss: 12, legendary: 19 },
  4: { mob: 8,  elite: 12, boss: 15, legendary: 24 },
  5: { mob: 9,  elite: 14, boss: 19, legendary: 29 },
  6: { mob: 11, elite: 17, boss: 22, legendary: 34 },
  7: { mob: 14, elite: 21, boss: 28, legendary: 43 },
  8: { mob: 17, elite: 26, boss: 33, legendary: 51 },
  9: { mob: 19, elite: 30, boss: 39, legendary: 60 },
};
// Two legitimate off-band shapes (enemy-scaling S-1). Anything else is a bug.
//   windup — a telegraphed 1-Clock windup reads ABOVE band; the party is paid in a
//            punish window. Capped so "telegraphed" cannot mean "arbitrary".
//   tick   — a per-Moment tick sits BELOW band; the tier ladder is what kills.
//   aura     — the strike is NOT where the threat is, so it legitimately reads BELOW
//              band. Floored at 0.5x so "aura" cannot excuse a token number: a boss
//              still has to hurt when it connects. e.g. THE MASKED's 6 against an F1
//              boss band of 8 — his countdown is the Dissolution aura, not the backhand.
//   presence — no attack AT ALL. Damage must be 0 and the note must say what the threat
//              is instead. This is the one exception the gate treats as a positive
//              claim rather than a tolerance: without it, a 125-budget boss authored
//              with no attack passes silently, which is the hole E-7 found.
// Mirrors models/Enemy.js. Defined here so --check runs with no node_modules.
const WEAKNESS_MODES = ['double', 'heal'];
const DAMAGE_EXCEPTIONS = { '': [1.0, 1.0], windup: [1.0, 2.0], tick: [0.2, 1.0], aura: [0.5, 1.0], presence: null };
const floorIdx = process.argv.indexOf('--floor');
const floor    = floorIdx !== -1 ? Number(process.argv[floorIdx + 1]) : 1;

const partsSum  = (e) => (e.bodyParts || []).reduce((a, p) => a + (p.maxHp || 0), 0);

const normPhase = (a) => JSON.stringify((a || []).map(p => ({ name: p.name, description: p.description, hpThreshold: p.hpThreshold })));
// sorted, so a reordered resistance list is not a spurious --force diff
const normRes   = (a) => JSON.stringify((a || []).map(r => ({ type: r.type, value: Number(r.value || 0) }))
                                         .sort((x, y) => String(x.type).localeCompare(String(y.type))));
const normUni   = (u) => JSON.stringify({ value: Number((u || {}).value || 0),
                                          cause: String((u || {}).cause || ''),
                                          removal: String((u || {}).removal || '') });
const normWeak  = (a) => JSON.stringify((a || []).map(w => (typeof w === 'string' ? { type: w, mode: 'double', why: '' }
                                          : { type: w.type, mode: String(w.mode || 'double'), why: String(w.why || '') }))
                                         .sort((x, y) => String(x.type).localeCompare(String(y.type))));
// 🔴 Was { name, maxHp } only, which meant the per-part `resistances`/`universal`
// added 2026-09-14 were INVISIBLE to the diff — editing THE MASKED's Mask universal
// or the Doorward's Torso gate produced no `bodyParts` difference and --force would
// not have written it. Fixed 2026-09-15 along with part-level weaknesses.
const normParts = (a) => JSON.stringify((a || []).map(p => ({
  name: p.name, maxHp: p.maxHp,
  resistances: normRes(p.resistances), universal: normUni(p.universal),
  weaknesses: normWeak(p.weaknesses),
})));
const normSig   = (g) => JSON.stringify({
  floor: Number((g || {}).floor || 0), damage: Number((g || {}).damage || 0),
  type: String((g || {}).type || ''), exception: String((g || {}).exception || ''),
  note: String((g || {}).note || ''),
});

/**
 * Seed-managed fields that differ between an existing doc and its seed.
 * Arrays are compared on their meaningful shape only, so Mongoose subdocument
 * bookkeeping never reads as a difference. Exported for testing without a DB.
 */
function diffFields(existing, seed) {
  const diffs = ['tier', 'size', 'color', 'description', 'notes']
    .filter(k => String(existing[k] || '') !== String(seed[k] || ''));
  if (normSig(existing.signature) !== normSig(seed.signature)) diffs.push('signature');
  if (normParts(existing.bodyParts) !== normParts(seed.bodyParts)) diffs.push('bodyParts');
  if (normPhase(existing.phases)    !== normPhase(seed.phases))    diffs.push('phases');
  if (normRes(existing.resistances) !== normRes(seed.resistances)) diffs.push('resistances');
  if (normUni(existing.universal)   !== normUni(seed.universal))   diffs.push('universal');
  if (normWeak(existing.weaknesses) !== normWeak(seed.weaknesses))  diffs.push('weaknesses');
  return diffs;
}

function esc(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

/** Doctrine gate — runs before any connection. Returns the report lines. */
/**
 * Rename gate. A seed may carry `renamedFrom: 'Old Name'` so a naming pass MOVES the
 * Atlas document instead of orphaning it — matching is by name (line ~336), so without
 * this a rename silently creates a second doc and leaves the old roster behind.
 * Cross-entry, so it runs once over the whole file rather than per entry.
 */
function renameProblems(seeds) {
  const out = [];
  const names = new Set(seeds.map(s => String(s.name || '').toLowerCase()));
  const seen = new Map();
  for (const e of seeds) {
    if (!('renamedFrom' in e)) continue;
    const from = String(e.renamedFrom || '').trim();
    if (!from) { out.push(`${e.name}: renamedFrom is empty — drop the key or name the old entry`); continue; }
    const key = from.toLowerCase();
    if (key === String(e.name || '').toLowerCase()) {
      // Report the specific fault only — a self-rename would otherwise also trip
      // the "another seed's live name" check below and say the same thing twice.
      out.push(`${e.name}: renamedFrom is its own name — nothing to migrate`);
      continue;
    }
    if (names.has(key)) {
      out.push(`${e.name}: renamedFrom "${from}" is another seed's live name — both would claim one document`);
    }
    if (seen.has(key)) {
      out.push(`${e.name}: renamedFrom "${from}" is already claimed by ${seen.get(key)}`);
    }
    seen.set(key, e.name);
  }
  return out;
}

function doctrineCheck(seeds, atFloor = floor) {
  const mobHp = FLOOR_MOB_HP[atFloor];
  if (!mobHp) throw new Error(`--floor ${atFloor} has no mob-HP entry (F1–F9 only)`);
  const problems = [];
  for (const e of seeds) {
    const ratio = RANK_RATIO[e.tier];
    if (!ratio) { problems.push(`${e.name}: unknown tier "${e.tier}" (mob|elite|boss|legendary)`); continue; }
    const want = mobHp * ratio, got = partsSum(e);
    const tol = TOLERANCE[e.tier];
    if (!tol) {
      // Mobs are exact: one meaningful hit, every time, on every floor.
      if (got !== want) problems.push(`${e.name}: mob part budget ${got}, doctrine wants exactly ${want} (F${atFloor})`);
    } else {
      const [lo, hi] = [Math.round(want * tol[0]), Math.round(want * tol[1])];
      if (got < lo || got > hi) {
        problems.push(`${e.name}: ${e.tier} part budget ${got} is outside ${lo}–${hi} ` +
                      `(§21.2 centre ${want} ±tolerance, F${atFloor})`);
      }
    }
    if (e.tier === 'mob' && (e.bodyParts || []).length !== 1) {
      problems.push(`${e.name}: mobs are ONE part (E-0.2), found ${(e.bodyParts || []).length}`);
    }
    if (e.tier !== 'mob' && (e.bodyParts || []).length < 2) {
      problems.push(`${e.name}: elite and above are MULTI-part (E-0.2), found ${(e.bodyParts || []).length}`);
    }
    if (e.tier !== 'mob' && !(e.notes || '').trim()) {
      problems.push(`${e.name}: ${e.tier} with no notes — every non-mob names its weak system (E-0.3)`);
    }
    if (!SIZES.includes(e.size)) {
      problems.push(`${e.name}: size "${e.size}" is not one of ${SIZES.join('|')} (§7.1)`);
    }
    problems.push(...damageProblems(e, atFloor));
    problems.push(...resistanceProblems(e, atFloor));
  }
  problems.push(...renameProblems(seeds));
  return problems;
}

/**
 * Signature-damage gate (enemy-scaling S-1). OPTIONAL BY DESIGN: an entry with no
 * `signature` (or floor 0) is skipped, so the existing rosters — whose damage still
 * lives in free-text notes — keep passing while they are migrated one at a time.
 * Once a signature IS present it is held to the band, with the four named exceptions.
 * Exported for testing without a DB.
 */
function damageProblems(e, atFloor) {
  const sig = e.signature;
  if (!sig || !Number(sig.floor)) return [];
  const out = [];
  const band = FLOOR_DAMAGE[Number(sig.floor)];
  if (!band) return [`${e.name}: signature.floor ${sig.floor} is not F1–F9`];
  const want = band[e.tier];
  if (!want) return [`${e.name}: signature on unknown tier "${e.tier}"`];
  const exc = String(sig.exception || '');
  if (exc === 'presence') {
    // A positive claim: this thing has no attack, on purpose, and here is why.
    if (Number(sig.damage || 0) !== 0) {
      out.push(`${e.name}: signature.exception "presence" means no attack — damage must be 0, got ${sig.damage}`);
    }
    if (!String(sig.note || '').trim()) {
      out.push(`${e.name}: signature.exception "presence" needs a note saying what the threat IS instead`);
    }
    if (Number(sig.floor) !== atFloor) {
      out.push(`${e.name}: signature.floor F${sig.floor} but the roster is being checked at F${atFloor}`);
    }
    return out;
  }
  const mult = DAMAGE_EXCEPTIONS[exc];
  if (!mult) {
    out.push(`${e.name}: signature.exception "${exc}" is not one of ` +
             `${Object.keys(DAMAGE_EXCEPTIONS).filter(Boolean).join('|')} (or empty for on-band)`);
    return out;
  }
  if (Number(sig.floor) !== atFloor) {
    out.push(`${e.name}: signature.floor F${sig.floor} but the roster is being checked at F${atFloor}`);
  }
  const got = Number(sig.damage || 0);
  const [lo, hi] = [Math.round(want * mult[0]), Math.round(want * mult[1])];
  if (got < lo || got > hi) {
    const label = exc ? `${exc} exception ${lo}–${hi}` : `on-band exactly ${want}`;
    out.push(`${e.name}: signature ${got} ${sig.type || ''}`.trim() +
             ` — F${sig.floor} ${e.tier} wants ${label} (enemy-scaling S-1)`);
  }
  if (got > 0 && !String(sig.type || '').trim()) {
    out.push(`${e.name}: signature has a number but no damage type`);
  }
  return out;
}


const RESIST_TYPES = ['Bleed', 'Crush', 'Burn', 'Chill', 'Poison', 'Infection', 'Dissolution'];

/**
 * Resistance gate (§10 / §10.1). Resistances are in FORCE.
 *
 * TYPED resistance subtracts from its own type only. UNIVERSAL resistance is the
 * same object as a damage threshold — universal 6 means "needs 7 Force to do
 * anything" — and the owner's rule is that it is ALWAYS CAUSED BY SOMETHING and
 * never a standing state. So this refuses any universal resistance that does not
 * name BOTH what causes it and what takes it away. A number nobody can answer is
 * not difficulty, it is a wall.
 *
 * ⚠️ NO TIER CHECK, deliberately. A MOB may carry any resistance, typed or
 * universal — that is E-0's "a mob that survives a hit gets a gate, never a fatter
 * number" working as intended, because a resistance IS that gate. Do not add one.
 *
 * Exported for testing without a DB.
 */
function resistanceProblems(e, atFloor = floor) {
  const out = [];
  // §21.3 — there is deliberately NO ceiling on a universal resistance. A boss may be
  // genuinely impossible for a build that brought the wrong things; the requirement is
  // that A PATH EXISTS, not that brute force is one of them. §10.1's mandatory
  // `removal` field is what guarantees the path, and it is enough.
  checkResistSet(e, e, `${e.name}`, out);
  // §7.3 resolves damage per part, so a PART may be warded while the body is not
  // (THE MASKED's Mask is sealed; the man is just a man). Same rules, same gate.
  (e.bodyParts || []).forEach((bp) => {
    if ((bp.resistances && bp.resistances.length) || Number((bp.universal || {}).value || 0)) {
      checkResistSet(bp, e, `${e.name} · part "${bp.name}"`, out);
    }
  });
  // §7.3 — a weakness answers a real damage type, and says how.
  checkWeaknessSet(e, e, `${e.name}`, out);
  (e.bodyParts || []).forEach((bp) => {
    if (bp.weaknesses && bp.weaknesses.length) {
      checkWeaknessSet(bp, e, `${e.name} · part "${bp.name}"`, out);
    }
  });
  return out;
}

/**
 * The weakness rules, applied to an enemy or to one of its parts.
 * `mode` is the field the Incinedile needed: 'double' is §7.3's rule, 'heal' is the
 * negative weakness (fire heals the boss). A PART overrides the body for its type —
 * fire heals the Incinedile and HARMS its Network, because mycelium burns — so a
 * part's weakness is checked against the PART's resistances, not the body's.
 */
function checkWeaknessSet(holder, e, label, out) {
  const ws = Array.isArray(holder.weaknesses) ? holder.weaknesses : [];
  const seen = new Set();
  ws.forEach((w, i) => {
    const ty = typeof w === 'string' ? w : String((w || {}).type || '');
    const mode = String((w || {}).mode || 'double');
    if (!RESIST_TYPES.includes(ty)) out.push(`${label}: weakness "${ty}" is not one of ${RESIST_TYPES.join('|')}`);
    if (seen.has(ty)) out.push(`${label}: weakness ${ty} is listed twice`);
    seen.add(ty);
    if (!WEAKNESS_MODES.includes(mode)) {
      out.push(`${label}: weakness[${i}] (${ty}) mode "${mode}" is not one of ${WEAKNESS_MODES.join('|')}`);
    }
    // A type cannot both be reduced and be doubled/healed by the SAME holder.
    if ((holder.resistances || []).some(r => r.type === ty)) {
      out.push(`${label}: ${ty} is listed as BOTH a weakness and a resistance — pick one`);
    }
    if (!String((w || {}).why || '').trim()) {
      out.push(`${label}: weakness[${i}] (${ty}) names no WHY — §21.3, same rule as resistances`);
    }
  });
}

/** The resistance rules, applied to an enemy or to one of its parts. */
function checkResistSet(holder, e, label, out) {
  const rs = Array.isArray(holder.resistances) ? holder.resistances : [];
  const seen = new Set();
  rs.forEach((r, i) => {
    const at = `${label}: resistances[${i}]`;
    const ty = String((r || {}).type || '');
    if (!RESIST_TYPES.includes(ty)) {
      out.push(`${at} type "${ty}" is not one of ${RESIST_TYPES.join('|')}`);
      return;
    }
    if (seen.has(ty)) out.push(`${at} duplicates ${ty} — one entry per type`);
    seen.add(ty);
    const v = Number((r || {}).value);
    if (!Number.isFinite(v) || v <= 0) out.push(`${at} (${ty}) value must be a positive number, got ${(r || {}).value}`);
    if (!String((r || {}).why || '').trim()) {
      out.push(`${at} (${ty}) names no WHY — §21.3, a resistance must trace to what the creature IS or has DONE. ` +
               `If you cannot write the reason, it is there to force a tactic and belongs cut.`);
    }
  });

  const u = holder.universal || {};
  const uv = Number(u.value || 0);
  if (uv < 0) out.push(`${label}: universal resistance cannot be negative (${uv})`);
  if (uv > 0) {
    if (!String(u.cause || '').trim()) {
      out.push(`${label}: universal ${uv} names no CAUSE — §10.1, a universal resistance is always the result of something, never a standing state`);
    }
    if (!String(u.removal || '').trim()) {
      out.push(`${label}: universal ${uv} names no REMOVAL — §10.1, every universal resistance must say what takes it away`);
    }

  }
}


/**
 * The connection string with the password blanked out, for logging.
 * A seed run gets pasted into chat, issues and commit messages routinely — the
 * banner must never be the thing that leaks a live Atlas credential.
 * (Learned the hard way 2026-08-25: a pasted runbook exposed the campaign
 * password and it had to be rotated.)
 */
function redactUri(uri) {
  return String(uri).replace(/(mongodb(?:\+srv)?:\/\/[^:@/]+:)[^@]*@/i, '$1****@');
}

async function run() {
  const seeds = require(seedFile.startsWith('.') ? path.join(__dirname, seedFile) : seedFile);
  if (!Array.isArray(seeds) || seeds.length === 0) throw new Error(`${seedFile} exported no enemies — refusing to run`);
  const dupes = seeds.map(s => s.name.toLowerCase()).filter((n, i, a) => a.indexOf(n) !== i);
  if (dupes.length) throw new Error(`Duplicate names inside the seed file: ${[...new Set(dupes)].join(', ')}`);

  const problems = doctrineCheck(seeds);
  if (problems.length) {
    console.error(`\n§21.2 doctrine check FAILED — ${problems.length} problem(s):`);
    problems.forEach(p => console.error(`  ✗ ${p}`));
    console.error('\nRefusing to run. Fix the seed file or pass the right --floor.');
    process.exit(1);
  }
  const m = FLOOR_MOB_HP[floor];
  const scale = `FORCE (§7.3) at floor ${floor} — a mob is one average swing`;
  console.log(`§21.2 doctrine check PASSED — ${seeds.length} entries, ${scale}: ` +
              `mob ${m} exact · elite ~${m * 12} · boss ~${m * 25} · super ~${m * 60}, ±tolerance.`);
  const spread = seeds.filter(e => e.tier !== 'mob').map(e => `${e.name} ${partsSum(e)}`).join(' · ');
  if (spread) console.log(`Non-mob spread: ${spread}`);
  if (checkOnly) { console.log('--check: doctrine only, no DB touched.'); return; }

  require('dotenv').config({ path: path.join(__dirname, '.env') });
  const mongoose = require('mongoose');
  const Enemy = require('./models/Enemy');

  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/galactic-prime-time';
  await mongoose.connect(uri);
  console.log(`${apply ? '=== APPLY MODE ===' : '=== DRY RUN (pass --apply to write) ==='}  ${redactUri(uri)}`);
  console.log(`Seed file: ${seedFile} — ${seeds.length} enem(y/ies)\n`);

  let created = 0, inSync = 0, diffed = 0, forced = 0, renamed = 0;
  for (const seed of seeds) {
    const { renamedFrom, ...doc } = seed;
    let existing = await Enemy.findOne({ name: new RegExp(`^${esc(seed.name)}$`, 'i') });
    let renaming = false;
    if (!existing && renamedFrom) {
      existing = await Enemy.findOne({ name: new RegExp(`^${esc(renamedFrom)}$`, 'i') });
      renaming = !!existing;
    }
    if (!existing) {
      created++;
      console.log(`+ CREATE  [${seed.tier}/${seed.size}]  ${seed.name} — ${partsSum(seed)} HP across ${seed.bodyParts.length} part(s)` +
                  `${seed.phases.length ? `, ${seed.phases.length} phase(s)` : ''}`);
      if (apply) await Enemy.create(doc);
      continue;
    }
    if (renaming) {
      renamed++;
      console.log(`> RENAME  ${renamedFrom}  ⇒  ${seed.name}  (same document, kept in place)`);
      if (apply) { existing.name = seed.name; await existing.save(); }
    }
    const diffs = diffFields(existing, seed);
    if (diffs.length === 0) { inSync++; continue; }
    if (force) {
      forced++;
      console.log(`~ FORCE   ${seed.name}  (overwriting: ${diffs.join(', ')})`);
      if (apply) { diffs.forEach(k => { existing[k] = seed[k]; }); await existing.save(); }
    } else {
      diffed++;
      console.log(`! EXISTS  ${seed.name} — differs on ${diffs.join(', ')} (kept as-is; --force to overwrite)`);
    }
  }
  console.log(`\n${created} ${apply ? 'created' : 'to create'} · ${inSync} in sync · ${forced} force-updated · ${diffed} left untouched` +
              `${renamed ? ` · ${renamed} ${apply ? 'renamed' : 'to rename'}` : ''}`);
  if (!apply) console.log('Dry run — nothing was written. Run backup-db.js first, then rerun with --apply.');
  await mongoose.disconnect();
}

module.exports = { doctrineCheck, damageProblems, resistanceProblems, renameProblems, diffFields, partsSum, WEAKNESS_MODES,
  FLOOR_MOB_HP, FLOOR_DAMAGE, RANK_RATIO, SIZES, TOLERANCE, DAMAGE_EXCEPTIONS };

if (require.main === module) run().catch(e => { console.error(e); process.exit(1); });
