/**
 * Floor 1 — the enemy roster. PROPOSAL, per rulebook/f1-enemy-pass.md.
 * Seed via: node seed-enemies.js            (dry run)
 *           node seed-enemies.js --apply
 *
 * Doctrine (rulebook §21.2, materials catalog M-1, F1 Forest band ×2):
 *   mob 5 · elite 60 · boss 125 · super 300 — as a PART BUDGET, not a pooled
 *   bar (f1-enemy-pass E-0.1). Mobs are ONE part at 5 (E-0.2). Anything that
 *   survives a hit does it through a GATE written into `notes`, never a fatter
 *   bar (E-0.3).
 *
 * `tier` uses the model's enum: mob | elite | boss | legendary.
 * §21.1 calls the fourth rank "Super Boss"; the model says `legendary`.
 */

// Mob: one part, 5 HP, no phases. The shape IS the doctrine.
const MOB = (name, { part = 'Body', ...o }) => ({
  tier: 'mob', name, size: 'Medium', phases: [],
  bodyParts: [{ name: part, maxHp: 5 }],
  ...o,
});

const E = (tier) => (name, o) => ({ tier, name, size: 'Medium', phases: [], ...o });
const ELITE = E('elite');
const BOSS  = E('boss');
const SUPER = E('legendary');

module.exports = [

  // ───────── Layer A — The Forest (shared, all routes) ─────────

  MOB('Bramblewretch', {
    part: 'Bramble Body',
    color: '#4a7a3a',
    description: 'A bundle of thorn-scrub that stood up. Appears 4-8 at a time and moves in straight lines.',
    notes: [
      'HORDE. 10 Bleed on contact. Moves in a straight line and does not turn well.',
      'GATE: none — this is the plain horde, the one the party learns cones on.',
      'Carve: none individually (E-0.4); a cleared room yields one F1 gather roll.',
    ].join('\n'),
  }),

  MOB('Husk-Moth Cloud', {
    part: 'Cloud',
    color: '#8a8fa8',
    size: 'Large',
    description: 'Statted and counted as ONE body, not a swarm of bodies. Blocks vision through its space.',
    notes: [
      '5 Chill to a random part per Moment in contact.',
      'GATE: immune to single-target damage. A sword through a cloud does nothing —',
      'cones, lines, area effects and Burn are the answer.',
      'This is the teaching mob for §21.2 "mob fights are about the crowd".',
    ].join('\n'),
  }),

  MOB('Rootjaw', {
    part: 'Rootjaw',
    color: '#6b4a2a',
    description: 'Buried ambusher. Never seen before it bites.',
    notes: [
      '10 Crush to a LEG from below; the target is Exposed for one Moment.',
      'GATE: untargetable while burrowed. Flushed by Burn on its square, sustained',
      'heavy noise, or Forest Resin poured on the ground (which also Clings it).',
      'Once surfaced it is simply a 5.',
    ].join('\n'),
  }),

  MOB('Spore-Drunk Contestant', {
    part: 'Body',
    color: '#7a6b45',
    description: 'A previous season\'s leftover, mycelium through the lungs. Still wearing the lanyard. Same network as the tutorial\'s Incineradile.',
    notes: [
      'Attacks with whatever it is still holding — 10 Crush.',
      'GATE: on death it puffs. 1-space cloud, Infected T1 to everything in it.',
      'Killing these badly costs you the floor. Range, fire, or spacing.',
      'GM: they are people, and they are on camera. §17 applies.',
    ].join('\n'),
  }),

  MOB('Glass-Antler Doe', {
    part: 'Body',
    color: '#cfe3f0',
    description: 'Skittish, luminous, worth money. It does not attack — it flees.',
    notes: [
      'GATE: Dodge Threshold 5 (§14). A mob that costs ammo and Moments, not HP.',
      'CARVE: Beastbone + Tough Hide (named quarry — the E-0.4 exception).',
    ].join('\n'),
  }),

  MOB('Camera Gnat', {
    part: 'Chassis',
    color: '#c0c0c8',
    size: 'Small',
    description: 'Corporation kit, not fauna. Hovers at head height and does not blink. No attack.',
    notes: [
      'GATE: social, not mechanical. Destroying one is trivial and costs Exposure',
      '(§17.1) — the crowd is watching through it. Free to kill, expensive to have killed.',
    ].join('\n'),
  }),

  ELITE('The Rack', {
    color: '#8b5a2b',
    size: 'Large',
    description: 'Antler-crowned stag. The forest\'s landlord. It does not charge; it waits, and the wood closes.',
    bodyParts: [
      { name: 'Crown',         maxHp: 8 },
      { name: 'Head',          maxHp: 10 },
      { name: 'Torso',         maxHp: 24 },
      { name: 'Foreleg L',     maxHp: 6 },
      { name: 'Foreleg R',     maxHp: 6 },
      { name: 'Hindquarters',  maxHp: 6 },
    ],
    notes: [
      'WEAK SYSTEM — the Crown. While the Crown is above 0, every OTHER part regains',
      '1 HP per Clock reset. Attrition against the body is a losing game and the party',
      'must notice why. Break the Crown (8) and the regrowth stops permanently.',
      '',
      'Attacks: gore 15 Bleed to torso. A 1-Clock windup stomp, 20 Crush to a leg, which',
      'leaves it Exposed for one Moment — that is the Crown\'s punish window.',
      '',
      'CARVE: Beastbone (guaranteed) + Mistletoe Sprig (rare, grown in the crown).',
      'The Mistletoe is the Easy route\'s answer to THE MASKED — see f1-enemy-pass E-3.',
    ].join('\n'),
  }),

  ELITE('Mycelium Bloomkeeper', {
    color: '#a0616a',
    size: 'Large',
    description: 'The network\'s gardener. It does not move from its patch, and its patch grows.',
    bodyParts: [
      { name: 'Bloom-Head',    maxHp: 12 },
      { name: 'Trunk',         maxHp: 24 },
      { name: 'Root Cord A',   maxHp: 4 },
      { name: 'Root Cord B',   maxHp: 4 },
      { name: 'Root Cord C',   maxHp: 4 },
      { name: 'Fruiting Arm L', maxHp: 6 },
      { name: 'Fruiting Arm R', maxHp: 6 },
    ],
    notes: [
      'GATE — surface immunity while tethered. All damage to Bloom-Head and Trunk is',
      'COSMETIC while any Root Cord lives. The Cords are visible, reachable, 4 HP each.',
      '',
      'WEAK SYSTEM — the Cords, and each one costs it something:',
      '  Cut A: it stops spreading spores.',
      '  Cut B: it stops re-rooting (it can no longer move its patch).',
      '  Cut C: the Fruiting Arms go limp.',
      'At ZERO Cords, damage lands normally.',
      '',
      'Attacks: spore burst (2-space, Infected T1); an Arm slam, 15 Crush.',
      'FIRE HEALS IT — exactly like the Incineradile. The tutorial\'s lesson restated',
      'on a creature where the answer is cutting, not burning.',
      '',
      'CARVE: Mycelium-Threaded Hide (second source of the Incineradile material).',
    ].join('\n'),
  }),

  // ───────── Layer B — Easy Route: the grand staircase ─────────

  MOB('Stair-Wight', {
    part: 'Body',
    color: '#5d6a7a',
    description: 'EASY ROUTE. The dungeon\'s previous visitors, still descending.',
    notes: [
      '10 Bleed, grabs at ankles (Slowed).',
      'GATE: it reforms. A Wight put down without Burn, dissolution, or being scattered',
      'down the stairwell stands back up at the next Clock reset, at 5.',
      'Teaching mob for "kill it properly, and mind the Clock".',
    ].join('\n'),
  }),

  ELITE('The Chainbearer', {
    color: '#7a7a8c',
    size: 'Large',
    description: 'EASY ROUTE. It has held this chain since before the mural was painted. It will not give it up, and it cannot follow you out of the room.',
    bodyParts: [
      { name: 'Head',  maxHp: 10 },
      { name: 'Torso', maxHp: 24 },
      { name: 'Arm L', maxHp: 6 },
      { name: 'Arm R', maxHp: 6 },
      { name: 'Leg L', maxHp: 7 },
      { name: 'Leg R', maxHp: 7 },
    ],
    notes: [
      'WEAK SYSTEM — the doorway. It cannot leave the mural chamber. The party does not',
      'have to beat it: the CHAIN can be worked free in 2 Moments under fire, and then',
      'they can simply go. Beating it is allowed, and slower.',
      '',
      'Attacks: chain sweep, 15 Crush in a 2-hex line; a grapple (§13) that pins against',
      'the mural.',
      '',
      'CARVE: Sinew Cord + the chain itself (baseline iron — the prophecy\'s chain is a',
      'story item, not a material).',
      '',
      'DESIGN: the first boss-doctrine lesson of the route, at elite cost — the win',
      'condition is a position, not a corpse.',
    ].join('\n'),
  }),

  BOSS('THE MASKED', {
    color: '#b8a13a',
    description: 'EASY ROUTE BOSS. The man who found the treasure. He is still in there. That is the problem.',
    bodyParts: [
      { name: 'Mask',  maxHp: 15 },
      { name: 'Head',  maxHp: 14 },
      { name: 'Torso', maxHp: 45 },
      { name: 'Arm L', maxHp: 12 },
      { name: 'Arm R', maxHp: 12 },
      { name: 'Leg L', maxHp: 13 },
      { name: 'Leg R', maxHp: 14 },
    ],
    notes: [
      'GATE — the Mask restores him. At every Clock reset the Mask returns ONE destroyed',
      'or disabled part to 1 HP, in the order it chooses. It is not the man that is durable.',
      '',
      'THE WIN CONDITION IS THE CHAIN, NOT THE KILL (§21.3). The prophecy is right.',
      'Chaining him needs the chain (Chainbearer), a pinned or Helpless target, and',
      '3 Moments of work. KILLING HIM IS POSSIBLE — and it costs this route its Floor 2',
      'and Floor 3, because he must be alive and chained at F2 and must become Nullrot',
      'at F3. DO NOT WARN THEM. The mural already did.',
      '',
      'THE MASK\'S WEAK SYSTEM — Oathbreaker. The Mask (15) cannot be damaged by normal',
      'harm. MISTLETOE ignores exactly that (M-1). A party that worked the forest layer',
      '(The Rack) arrives holding the answer; a party that skipped it chains him the hard',
      'way, which is the intended baseline.',
      '',
      'CARVE: none — he lives, and that is the point. The collapse yields an Oak Heartwood',
      'and an Obsidian Shard gather on the way out.',
    ].join('\n'),
    phases: [
      { name: 'Wearing It', hpThreshold: 'opening — 61 total',
        description: 'He still speaks, in his own voice, and he apologises between attacks. Backhand 15 Crush; a grab that pulls a contestant to the mural.' },
      { name: 'The Mask Speaks', hpThreshold: '<=60 total',
        description: 'The voice changes. Gains a Dissolution aura: any contestant who ends a Clock adjacent begins Dissolution (§8.2 — one Clock of grace, then the Hold Threshold). ESCALATION +1 PER MOMENT: it is a haunted object, not a god. Leaving the aura freezes the threshold where it stands; it never resets. The room stops being a fight and starts being a countdown, and the GM says the remaining Moments out loud.' },
      { name: 'The Collapse', hpThreshold: '<=25 total, OR the chain is set',
        description: 'The ceiling starts coming down. 3-Clock timer to be out. Falling stone is environmental (§14: never dodged). If the chain is set he stops fighting and watches them leave.' },
    ],
  }),

  // ───────── Layer C — Medium Route: the haunted house ─────────

  MOB('Torchbearer', {
    part: 'Body',
    color: '#c25b2a',
    description: 'MEDIUM ROUTE. Rank and file of the arsonist NPC party. Human. Frightened, and doing it anyway.',
    notes: [
      'Torch, 10 Burn; or a tool, 10 Crush.',
      'GATE: none — and that is the encounter\'s whole weight. They die in one hit, they',
      'are people, and the cameras are running (§17).',
    ].join('\n'),
  }),

  ELITE('The Kindler', {
    color: '#e07b2a',
    description: 'MEDIUM ROUTE. Carries the fuel. Enjoys the work.',
    bodyParts: [
      { name: 'Head',             maxHp: 10 },
      { name: 'Torso',            maxHp: 22 },
      { name: 'Arm L',            maxHp: 6 },
      { name: 'Arm R',            maxHp: 6 },
      { name: 'Leg L',            maxHp: 6 },
      { name: 'Leg R',            maxHp: 6 },
      { name: 'Fuel Can (worn)',  maxHp: 4 },
    ],
    notes: [
      'WEAK SYSTEM — he is his own liability. The Fuel Can is a targetable worn part at',
      '4 HP. BURN 25 ON THE CAN detonates it: 3-space radius, 10 Burn — the Incineradile\'s',
      'trash-can rule, on a person who chose to carry it. The party does not have to',
      'out-damage him; they have to light him.',
      '',
      'Attacks: thrown fire, 15 Burn in a 2-space splash; sets terrain alight',
      '(§21.4 — flammable ground).',
      '',
      'CARVE: Forest Resin (what he thickened the fuel with).',
    ].join('\n'),
  }),

  BOSS('Foreman Bex', {
    color: '#a03a3a',
    description: 'MEDIUM ROUTE BOSS. The NPC party\'s leader. Reasonable, articulate, and burning a house with a child in it. NAME IS A PROPOSAL — it becomes canon at F3, where he runs the human farm.',
    bodyParts: [
      { name: 'Head',  maxHp: 14 },
      { name: 'Torso', maxHp: 45 },
      { name: 'Arm L', maxHp: 12 },
      { name: 'Arm R', maxHp: 12 },
      { name: 'Leg L', maxHp: 13 },
      { name: 'Leg R', maxHp: 13 },
      { name: 'Pack',  maxHp: 16 },
    ],
    notes: [
      'HE MUST SURVIVE THIS FLOOR — he is the F3 human-farm operator (Compendium §4.4).',
      '',
      'THE WIN CONDITION IS THE HOUSE, NOT THE MAN (§21.3). Three ways this ends, and',
      'ALL THREE ARE WINS:',
      '  - the fire is put out, or',
      '  - the girl is out of the house, or',
      '  - his HP total drops to <=40.',
      'On any of them he DISENGAGES — takes the surviving Torchbearers and goes, covering',
      'the retreat. He cannot be killed on this floor; if cornered, the fire takes the',
      'front of the house and he is gone in the smoke. If that reads as a cheat at the',
      'table, the honest fix is to make the smoke visible early, not to change the ruling.',
      '',
      'CARVE: none — human. YIELDS: the ledger from the Pack if the Pack was brought to 0.',
      'It names the buyers — the only F1 way to reach F3\'s farm already knowing what it is.',
    ].join('\n'),
    phases: [
      { name: 'The Burning', hpThreshold: 'opening — 81 total',
        description: 'He directs; the Torchbearers work. He fights defensively and talks the entire time. He will negotiate. He is lying.' },
      { name: 'Ugly Work', hpThreshold: '<=80 total',
        description: 'He stops directing and starts fighting. 20 Crush, two attacks a Clock; drags a contestant into the burning doorway.' },
      { name: 'Cut and Run', hpThreshold: '<=40 total, OR fire out, OR girl out',
        description: 'Disengage. He takes the surviving Torchbearers and covers the retreat. The Pack comes off if it was destroyed — it holds the ledger (F3 hook).' },
    ],
  }),

  BOSS('The Girl in the House', {
    color: '#6a2a6a',
    size: 'Small',
    description: 'MEDIUM ROUTE. She is what the NPCs were right about. She is also a child in a burning house, and both are true. Killable — and killing her mortgages Floors 2 and 3.',
    bodyParts: [
      { name: 'Head',   maxHp: 14 },
      { name: 'Torso',  maxHp: 45 },
      { name: 'Arm L',  maxHp: 12 },
      { name: 'Arm R',  maxHp: 12 },
      { name: 'Leg L',  maxHp: 13 },
      { name: 'Leg R',  maxHp: 13 },
      { name: 'Shadow', maxHp: 16 },
    ],
    notes: [
      'SHE CAN BE KILLED (owner ruling 2026-08-18). The 125 is real, there is no gate and',
      'no special weak system — she is a demon in a burning house and she can be put down.',
      'WHAT IT COSTS IS THE FLOOR ABOVE. Killing her is a win that mortgages F2 and F3:',
      '',
      '  1. THE THRONE EMPTIES. She was the DIRECTOR, and nothing about her death replaces',
      '     her. Her god collapses with her — no queen, no congregation, no prayers.',
      '  2. BEELZEBUB TAKES THE VACANCY, AND HE USES THE RIVAL. The demon who helped humans',
      '     and wanted to overthrow her is exactly the useful shape: already positioned,',
      '     already ambitious, already trusted by the humans he protected. He does not know',
      '     whose instrument he has become, and neither does the party.',
      '  3. THE DEMONS WHO DID NOT BEND THE KNEE ARE JUST RAMPAGING MONSTERS. Leaderless,',
      '     agenda-less, pure threat. This is why the rampage gets WORSE and not better —',
      '     it is a schism, not an absence.',
      '  4. F2 FLIPS. The assassination beat still happens, but the rival is now Beelzebub\'s',
      '     viceroy rather than a rebel — the party is either killing his man, or being',
      '     hired by him and not told by whom.',
      '  5. F3: BEX RUNS THE FARM UNDER BEELZEBUB\'S WATCHING EYE, AND THAT IS THE ONLY',
      '     REASON IT IS STILL INTACT. The humans inside are alive because they are useful',
      '     to a Prince of Demons; the ones outside are hunted in the dark by the unbent.',
      '     The farm stops being an atrocity and becomes PROTECTION, sold at a price.',
      '     Foreman Bex\'s ledger is a Beelzebub document and he may not know it.',
      '',
      'SPARING HER is the other bill: the brand\'s price, and a demonic queen at F2 — but the',
      'rival stays a real rebel and Beelzebub never gets a foot in the capital at all.',
      'NEITHER OPTION IS SAFE, and the party will not learn that until Floor 3.',
      '',
      'HER F1 ROLE IS STILL THE BRAND. She asks to be fed; she grants the demonic brand',
      '(immunity to noble-class presence/Dissolution — what the F2 Demonic Noble encounter is',
      'built around) plus faction points.',
      '',
      'PRESENCE: noble-class. An UNBRANDED contestant who refuses her, in the room, begins',
      'Dissolution (§8.2). ESCALATION +2 PER MOMENT — she is noble-class, and at F2 she is a',
      'queen. Half the Moments of a haunted object. Tell them the number out loud.',
    ].join('\n'),
  }),

  // ───────── Layer D — Hard Route: the moving city ─────────

  MOB('Crystallized Citizen', {
    part: 'Body',
    color: '#9ad4e0',
    description: 'HARD ROUTE. They are still standing where they stopped. Some are mid-sentence, and all of them are facing the same way — toward wherever the mist was.',
    notes: [
      '10 Crush, slow, and it will follow you across the whole floor.',
      '',
      'IT IS A HOST, NOT SCENERY. The crystal is a DISEASE and this is what it built.',
      'It is not finished with them and it is trying to reach you: contact spreads',
      '(see the Crystal Spore Mist). BREAKING IT IS THE CURE, and it is also killing a',
      'person who is still in there. That is the floor\'s whole argument.',
      '',
      'GATE: BLEED DOES NOTHING — there is nothing left in it to bleed. CRUSH ONLY.',
      'Burn and Chill are cosmetic; Poison and Infection have no entry condition (§8.2).',
      'The party\'s Bleed-heavy F1 kit is suddenly the wrong kit — and the only thing that',
      'works is the thing that shatters them. The gate is the horror, not a puzzle.',
      '',
      'CARVE (room gather, E-0.4): Obsidian Shard — the crystal is close enough to work.',
      'Taking it is looting a person. Nobody will stop you.',
      '',
      'GM: these are the citizens the Loong is guarding. Every one the party breaks is',
      'evidence for the argument they are about to make — and a thing they did to a person.',
      'Do not editorialise; just keep count where they can see it.',
    ].join('\n'),
  }),

  MOB('Crystal Spore Mist', {
    part: 'Mist',
    size: 'Large',
    color: '#bfe9f5',
    description: 'HARD ROUTE. A twinkling mist. It is genuinely beautiful, it drifts toward warmth, and it is the single most dangerous thing on Floor 1.',
    notes: [
      'THE VECTOR. Statted and counted as ONE body, like the Husk-Moth Cloud — the forest',
      'layer already taught the party what to do with a cloud. This one is worse.',
      '',
      'IT TEMPTS. It glitters like a find. NO ROLL — the party walks toward it or they do',
      'not, and that is the point (§6: there are no to-hit rolls, and this is a choice, not',
      'a save). Every crystallized citizen on this floor walked toward it. Their poses say',
      'so, and a party that looks will notice they are all facing the same way.',
      '',
      'GATE: immune to single-target damage. Cones, lines, area and wind move it; a sword',
      'does nothing. Burn disperses a 2-space pocket for one Clock.',
      '',
      'TWO EXPOSURE ROUTES, AND THEY ARE NOT THE SAME (proposal, E-0.6):',
      '  CONTACT — it crystallizes on whatever it touches. INFECTED T1 on that PART,',
      '    advancing per §8.1. Localized, visible, and it can be broken off a limb.',
      '  INHALATION — the airway closes with crystal. INFECTED T1 *plus* SUFFOCATION',
      '    (§8.2 — torso only, tierless 2-Clock death timer). This is the deadly one, and',
      '    it is deadly immediately. Pneumotoxin is the precedent (§8.2: "starts the',
      '    Suffocation timer once it reaches the torso").',
      '  INFECTED T3 KILLS NORMALLY (ruled 2026-08-18) — the book\'s own 2-Clock death',
      '    timer, and that timer IS the mercy window. No statue, no special case: a',
      '    contestant crystallised until F3 is out of play either way. All the drama lives',
      '    at T1-T2 where Resin, Antiseptic Wash and Burn T2 can still reach it.',
      '',
      'SAFETY MEASURES EXIST AND MOSTLY ALREADY SHIPPED (E-6):',
      '  - A sealed respirator stops INHALATION, not contact.',
      '  - FOREST RESIN smeared on skin and gear: the crystal grips the resin and is peeled',
      '    off with it. One coat per exposure. The F1 forest sells the F1 answer again.',
      '  - Antiseptic Wash (Batch A, already in the library) — -1 Infected tier per use.',
      '  - BURN T2 clears infection outright (§8.2). Cauterising a crystallising limb works,',
      '    it is in the book already, and it is exactly as ugly as it sounds.',
      '',
      'CARVE: none. Do not let anyone bottle it. If they try, that is a story, not a loot roll.',
    ].join('\n'),
  }),

  ELITE('Step-Warden', {
    color: '#7a8fa0',
    size: 'Huge',
    description: 'HARD ROUTE. An ambulatory section of staircase. The city built its own guards out of itself.',
    bodyParts: [
      { name: 'Crown Block',   maxHp: 12 },
      { name: 'Body Mass',     maxHp: 26 },
      { name: 'Keystone',      maxHp: 6 },
      { name: 'Leg Column L',  maxHp: 8 },
      { name: 'Leg Column R',  maxHp: 8 },
    ],
    notes: [
      'GATE — surface immunity. Damage to Crown Block and Body Mass is cosmetic. It is masonry.',
      '',
      'WEAK SYSTEM — the Keystone, in its back. 6 HP, unreachable while it faces you.',
      'Exposed ONLY during its stomp: a 1-Clock windup, 25 Crush in a 2-space square, after',
      'which it is Exposed for one Moment (§11) and the Keystone is reachable. Bait it,',
      'get behind it, or have someone tall.',
      '',
      'CARVE: Obsidian Shard (guaranteed, from the Keystone).',
    ].join('\n'),
  }),

  SUPER('Loong Kin', {
    color: '#2a8f7a',
    size: 'Huge',
    description: 'HARD ROUTE SUPER BOSS. Two forms. WARDEN FORM: a woman, 2.5m, towering over everyone in the room. LOONG FORM: the size of buildings — hundreds of metres, and it does not obviously end. It has guarded a city that has been empty for a very long time. Nobody has told it. It is not stupid; it is loyal, which is worse.',
    bodyParts: [
      { name: 'Head',              maxHp: 30 },
      { name: 'Neck',              maxHp: 25 },
      { name: 'Body Coil (fore)',  maxHp: 55 },
      { name: 'Body Coil (mid)',   maxHp: 55 },
      { name: 'Body Coil (rear)',  maxHp: 45 },
      { name: 'Foreclaw L',        maxHp: 20 },
      { name: 'Foreclaw R',        maxHp: 20 },
      { name: 'Whiskers',          maxHp: 10 },
      { name: 'Tail',              maxHp: 40 },
    ],
    notes: [
      'TWO FORMS. The encounter opens in WARDEN FORM and should, if it goes well, never',
      'leave it.',
      '  WARDEN FORM — a woman, 2.5m, towering. SIZE: LARGE. This is who you talk to.',
      '  LOONG FORM  — buildings. Hundreds of metres, and it does not obviously end.',
      '                SIZE: HUGE. The 300-point statline below IS this form.',
      'The `size` field carries HUGE because that is the form the combat rules read.',
      '',
      'THE SIZE DIFFERENCE IS THE TRAP, AND IT FALLS OUT OF THE BOOK.',
      'Warden Form is LARGE — exactly ONE size larger than a Medium contestant — so',
      'GRAPPLING HER IS LEGAL (§13). Loong Form is HUGE, two sizes larger, so it cannot',
      'be grappled at all, and §21.3 makes it immune to grapple-Suffocation besides.',
      'You can lay hands on the woman. You cannot lay hands on the dragon. Doing the',
      'first causes the second. Do not warn them; let the size line do the work.',
      '',
      'WARDEN FORM HAS NO SEPARATE HP POOL. The first meaningful wound (or any grapple)',
      'triggers the Turn, and the Loong enters at a FULL 300. Hitting her is strictly',
      'worse than not hitting her. There is no cheap window and no chip damage.',
      '',
      'THE WIN CONDITION IS THE CONVERSATION, AND THE CONVERSATION IS NOW MUCH WORSE.',
      'The statline exists so that "let\'s just fight it" is legible as a bad idea FROM THE',
      'NUMBERS, before anyone commits. Per §21.3 the position that makes a killing hit',
      'possible is here a sentence — but it is no longer the easy sentence "the city is',
      'abandoned", which it could go and check. It is:',
      '',
      '    Your people are not gone. They are in there. And the only way to free them is',
      '    to break them — and we will have to do it in front of you.',
      '',
      'Evidence beats rhetoric: a crystallized citizen carried up the stairs is the',
      'argument. Charm helps; PROOF lands. And because it cannot be lied to, the party',
      'cannot soften it — they have to say the true, terrible thing to its face and have',
      'it believed.',
      '',
      'THE TRUTH-SENSE IS THE TELL, and it runs in BOTH forms — the Whiskers (10) are',
      'only where you can SEE it. It reads truth at close range. A party that notices can',
      'work out that it CANNOT BE LIED TO, which is why the honest argument is the only',
      'one that works, and why attacking the Whiskers to "blind" it is the worst move',
      'available.',
      '',
      'IT SURVIVES. It is escorted at F2 and hides in the capital at F3. If the party kills',
      'it, that route ends at F1 and the owner should be told at the table what they spent.',
      '',
      'CARVE: NONE. Loong-Scale is SHED, NOT TAKEN (materials catalog M-5 — APEX/DIVINE,',
      'authored-only, never pooled, never sold). If it is persuaded, it sheds one scale,',
      'freely, as thanks. That is the only way that material enters the world.',
    ].join('\n'),
    phases: [
      { name: 'Warden Form', hpThreshold: 'the encounter opens here',
        description: 'A woman, 2.5m, and she has to look down at everyone. SIZE: LARGE — grappleable, one size up. She is polite, she is patient, and she has been patient for a very long time. This is the whole encounter if the party is any good: make the argument, bring the evidence, and never touch her. She has no separate HP pool.' },
      { name: 'The Turn', hpThreshold: 'first meaningful wound, OR any grapple, OR the argument fails',
        description: 'She unfolds. Buildings; hundreds of metres of her, and the far end is somewhere out past the stairs. SIZE: HUGE — no longer grappleable at all (§13). The Loong enters at a FULL 300; nothing done to the Warden carries over. It does not retaliate on the first Clock. It coils, and it says so. That Clock is the last exit.' },
      { name: 'The Coil', hpThreshold: '<=240 total',
        description: 'It stops being polite. Constriction — two-plus sizes larger, so the party cannot grapple it and it is immune to grapple-Suffocation (§13/§21.3). 30 Crush, and it repositions the fight onto the stairs where falling applies (§21.5).' },
      { name: 'Storm-Breath', hpThreshold: '<=150 total',
        description: 'A 10-hex line, 30 Chill, terrain becomes difficult (§21.4). Dodge Threshold 7 with the §14 counter-ladder: Reflexes 7 auto-dodge + 1 space, Reflexes 9 auto-dodge + counterattack, below 7 the 1d4 fallback.' },
      { name: 'It Decides You Are Not Contestants', hpThreshold: '<=60 total',
        description: 'It stops treating the fight as an interruption. A TPK is the expected outcome and the GM should say so out loud when this phase opens. Retreat is still open; the stairs are long, and it is longer.' },
    ],
  }),
];
