/**
 * Floor 3 — the grand capital, a hundred years after Floor 2 (170 after Floor 1).
 * PROPOSAL, per rulebook/f3-enemy-pass.md. Set 1's finale; the capital then attaches
 * to the Lounge as a persistent location (Compendium §4.1).
 *
 * BAND UNITS (§12.7 errata). HP identical to F1/F2: mob 5 exact · elite ~60 ±tol ·
 * boss ~125 ±tol · super ~300. Damage: mob 6 · elite 9 · boss 12 · super 19.
 * Carves are M-3 Capital: Jade · Mirror-Bronze · Silver · Inscribed Clay ·
 * Orichalcum · Cursed Gold ⭐.
 *
 * DESIGN RULE FOR THIS FLOOR (owner, 2026-08-18): every mob is a CONSEQUENCE of a
 * previous floor, not a thing that happens to be here. The capital is where the
 * party finds the climax of the story they have been in since Floor 1 — and they
 * may perform it however they like. This is NOT a stealth floor.
 */

const MOB = (name, { part = 'Body', ...o }) => ({
  tier: 'mob', name, size: 'Medium', phases: [],
  bodyParts: [{ name: part, maxHp: 5 }],
  ...o,
});
const E = (tier) => (name, o) => ({ tier, name, size: 'Medium', phases: [], ...o });
const ELITE = E('elite');
const BOSS  = E('boss');
const SUPER = E('legendary');

module.exports = [

  // ───────── Layer A — The Grand Capital (shared, all routes) ─────────

  MOB('Quarantine Enforcer', {
    part: 'Body',
    color: '#5d6b7a',
    description: 'F3 SHARED. Masked, gloved, carrying fire. They seal districts that cough, and they do not open them again.',
    notes: [
      '6 Burn from a hooked torch. They work in threes and they do not chase.',
      '',
      'GATE: none — and that is the difficulty. THEY ARE PROBABLY RIGHT. The capital has',
      'held the crystal off for a century this way. The party is inside a quarantine whose',
      'terms they never read, and every one of these is a person doing a job that works.',
      '',
      'CONSEQUENCE OF: the plague getting out. The quarantine exists because it reached the',
      'capital — and on the Easy route the party is why (F2 Doorward).',
      '',
      'The sealed districts are a PLACE, not an obstacle: half the floor is behind that line,',
      'the people inside are still alive, and getting in is easy. Getting back out is the ask.',
    ].join('\n'),
  }),

  MOB('Infected Citizen', {
    part: 'Body',
    color: '#9ab08a',
    description: 'F3 SHARED. Not crystal yet. Coughing, frightened, and still entirely themselves — which is the problem.',
    notes: [
      '6 Crush with whatever is to hand. They fight because they are cornered, not because',
      'they want to, and they will stop the moment they are given a way out.',
      '',
      'GATE: none. THEY ARE CURABLE. Antiseptic Wash, Burn T2, or twenty minutes near',
      'Nullrot\'s Halo, and they are people again. Every one the party kills was a person',
      'they could have kept — and §17 is watching them decide which.',
      '',
      'CONSEQUENCE OF: F1\'s crystal, seventy years of F2\'s desert, and whatever the party',
      'did about either. A Hard-route party knows exactly what these become.',
    ].join('\n'),
  }),

  MOB('Rogue Demon', {
    part: 'Body',
    color: '#8a2f5a',
    description: 'F3 SHARED. Leaderless, agenda-less, and in the city. It is not hunting anything. It is just here.',
    notes: [
      '6 Bleed, fast, and it does not retreat because nothing told it to.',
      '',
      'GATE: none. It is the plain horde of the capital and it dies like one.',
      '',
      'CONSEQUENCE OF: THE FLOOR-1 RULING ON THE GIRL, directly.',
      '  SHE WAS KILLED → the demons who did not bend the knee to Beelzebub are these.',
      '    They are EVERYWHERE, in numbers, and the city has no idea why it got worse.',
      '  SHE WAS SPARED → far fewer, and they still have orders, which means they can be',
      '    talked to, bribed, or reported to a court that will discipline them.',
      'Same statline. The count and the conversation change. The party made this.',
    ].join('\n'),
  }),

  MOB('Hoodlum', {
    part: 'Body',
    color: '#6a6050',
    description: 'F3 SHARED. A quarantine is an economy. These are the people running it.',
    notes: [
      '6 Bleed with a knife they know how to use. They rob, they do not murder, and they',
      'will absolutely murder if it looks like the alternative.',
      '',
      'GATE: none — but they KNOW THE WALLS. Every one of them can get through the',
      'quarantine line, and one that is beaten rather than killed will sell that route',
      'cheaply. They are the floor\'s best map and its worst witnesses.',
      '',
      'CONSEQUENCE OF: the quarantine itself. Seal a city and this is what grows in it.',
    ].join('\n'),
  }),

  MOB('Crystal Cluster', {
    part: 'Cluster', size: 'Large',
    color: '#a9dbe8',
    description: 'F3 SHARED, dense on the Easy and Hard routes. It grows out of a wall, a cart, a person. It does not move and it does not want anything.',
    notes: [
      'NO ATTACK. It is terrain until touched.',
      '',
      'GATE: DAMAGING IT SPREADS IT. Any hit that is not Burn bursts it — 2-space cloud,',
      'Infected T1, regrowing within a Clock from whatever it landed on.',
      'BURN DESTROYS IT CLEANLY (§8.2 — Burn T2 clears infection) and leaves nothing.',
      '',
      'CONSEQUENCE OF: the plague, and the party\'s F1 route. A Hard-route party has seen',
      'this before, on a smaller city, with people still inside it.',
      '',
      'ALSO: F1\'s CRYSTALLIZED CITIZENS RETURN AS A TIDE (~50, enemy-scaling S-2) inside',
      'the sealed districts — still Crush-only, still people, and now there are fifty.',
    ].join('\n'),
  }),

  ELITE('Mirror-Bronze Warden', {
    size: 'Large',
    color: '#b8a06a',
    description: 'F3 SHARED. A city guardian polished every morning for four hundred years, by nobody, lately.',
    bodyParts: [
      { name: 'Polished Face', maxHp: 14 },
      { name: 'Head',          maxHp: 10 },
      { name: 'Torso',         maxHp: 26 },
      { name: 'Arm L',         maxHp: 8 },
      { name: 'Arm R',         maxHp: 8 },
      { name: 'Leg L',         maxHp: 5 },
      { name: 'Leg R',         maxHp: 4 },
    ],
    notes: [
      'GATE — IT REFLECTS. Any ranged attack, thrown weapon, cone, line or skill effect that',
      'strikes it is turned back on the attacker at full value. Melee is unaffected.',
      '',
      'WEAK SYSTEM — the Polished Face (14). Dull it and the reflection stops: acid, soot,',
      'mud, blood, Forest Resin, or simply breaking it.',
      '',
      'CONSEQUENCE OF: nothing the party did — it is the capital being OLD, and the one',
      'thing on this floor that predates their whole story. It is guarding something and',
      'it has forgotten what.',
      '',
      'Attacks: a shield-edge chop, 9 Crush. It advances and does not pursue.',
      'CARVE: Mirror-Bronze.',
    ].join('\n'),
  }),

  ELITE('Silver-Limbed Surgeon', {
    color: '#c8ccd2',
    description: 'F3 SHARED. It has been replacing what the crystal takes, for longer than anyone asked it to.',
    bodyParts: [
      { name: 'Head',         maxHp: 7 },
      { name: 'Torso',        maxHp: 15 },
      { name: 'Silver Arm L', maxHp: 6 },
      { name: 'Silver Arm R', maxHp: 6 },
      { name: 'Leg L',        maxHp: 5 },
      { name: 'Leg R',        maxHp: 5 },
    ],
    notes: [
      'GATE — IT WILL NOT LET YOU DIE. Any contestant reduced to bleed-out (§7.5) in its',
      'reach is STABILISED, mid-fight, whether they want that or not — and it takes the part',
      'it judges beyond saving. The replacement is Silver, and it works.',
      '',
      'WEAK SYSTEM — it can be TALKED TO, and it is the only thing on this floor that can be.',
      'It is not hostile; it is unsupervised. Give it a patient and it stops fighting.',
      'Killing it is easy, cheap, and loses the party the best surgeon in the capital right',
      'before a floor that will take limbs off them.',
      '',
      'CONSEQUENCE OF: a century of Infected Citizens. Somebody had to do this.',
      '',
      'Attacks: a precise cut, 9 Bleed, aimed at a limb and never at a lethal part.',
      'CARVE: Silver — the prosthetic metal, body-part replacement gear (M-3 ⚖).',
    ].join('\n'),
  }),

  // ───────── Layer B — Easy Route: Nullrot ─────────

  MOB("Nullrot's Faithful", {
    part: 'Body',
    color: '#7a8c5a',
    description: 'EASY ROUTE. He cured them. Some of them a hundred years ago. They have not left.',
    notes: [
      '6 Crush, with whatever the street provided.',
      '',
      'GATE: THEY WILL NOT RAISE A HAND TO HIM AND THEY WILL DIE FOR HIM. They interpose',
      'bodily, unarmed, without threat, and without stopping. Killing them is trivial, and',
      'it is the whole scene.',
      '',
      'CONSEQUENCE OF: the cure working. This is what a hundred years of it looks like.',
    ].join('\n'),
  }),

  ELITE('The First Cured', {
    color: '#8fa87a',
    description: 'EASY ROUTE. The first person he saved, a hundred and seventy years ago. Still alive. Still, in places, crystal.',
    bodyParts: [
      { name: 'Head',             maxHp: 11 },
      { name: 'Torso',            maxHp: 24 },
      { name: 'Crystal Shoulder', maxHp: 9 },
      { name: 'Arm L',            maxHp: 7 },
      { name: 'Arm R',            maxHp: 6 },
      { name: 'Leg L',            maxHp: 5 },
      { name: 'Leg R',            maxHp: 4 },
    ],
    notes: [
      'GATE — THE CRYSTAL SHOULDER (9) IS NOT A WEAKNESS, IT IS THE PROOF. It has not grown',
      'in a century and it has not gone, which is how anyone knows the cure ARRESTS the',
      'plague rather than removing it. Destroy the shoulder and it dies — that is the part',
      'the cure is holding.',
      '',
      'WEAK SYSTEM — it does not want to fight and says so at length. It guards the way to',
      'Nullrot out of gratitude, and gratitude ARGUES. Convince it the party means him no',
      'harm and it stands aside.',
      '',
      'KILLING IT DESTROYS THE EVIDENCE. A party that does reaches Nullrot with no reason',
      'to believe anything he says.',
      '',
      'CONSEQUENCE OF: the mask, the staircase, and a man who was chained instead of killed.',
      '',
      'Attacks: 9 Crush, apologetic, and it pulls its blows.',
      'CARVE: none — it is a person. Yields: a century of notes on the disease.',
    ].join('\n'),
  }),

  SUPER('Nullrot', {
    size: 'Large',
    color: '#5f7a4a',
    description: 'EASY ROUTE FINALE. The man from the staircase. He is spreading a disease and curing it, in the same street, on the same day, and both are true.',
    bodyParts: [
      { name: 'Mask',          maxHp: 30 },
      { name: 'Head',          maxHp: 26 },
      { name: 'Torso',         maxHp: 70 },
      { name: 'Arm L',         maxHp: 24 },
      { name: 'Arm R',         maxHp: 24 },
      { name: 'Leg L',         maxHp: 26 },
      { name: 'Leg R',         maxHp: 26 },
      { name: 'The Reservoir', maxHp: 40 },
      { name: 'Halo of Cures', maxHp: 34 },
    ],
    notes: [
      'THE CANON BEAT (Compendium §4.2): he is simultaneously spreading and curing a disease',
      'in the capital, and the party chooses to fight or to help.',
      '',
      'HE IS BOTH PATIENT ZERO AND THE ANTIBODY (ruled). That is a body, not a paradox: THE',
      'RESERVOIR (40) holds the plague, THE HALO OF CURES (34) is what he sheds walking down',
      'a street. He cannot have one without the other, and neither can anyone else.',
      '',
      'THE PARTY DID THIS. The Doorward at F2 had been eating the plague out of him for',
      'seventy years. They killed it to free him — correctly, on the evidence they had — and',
      'the reservoir has been filling ever since. Nobody needs to tell them. Someone will.',
      '',
      'FIGHTING HIM IS LEGIBLE AS A BAD IDEA FROM THE NUMBERS, as the Loong was. THE WIN',
      'CONDITION IS THE ARGUMENT (§21.3), and it is hard, because he is right: killing him',
      'ends the cure, and the capital has a century of people alive only because of the Halo.',
      '',
      'DESTROYING THE RESERVOIR (40) ALONE is the surgical answer. It is deep, it is guarded,',
      'and it takes the Mask down first. It ends the plague and leaves the cure. It also,',
      'almost certainly, ends him — and the party will not be told that until afterwards.',
      '',
      'THE MASK (30) is the same mask, and it is what carries the plague; he is only its',
      'newest host. Removing it is not a kill, it is a burial.',
      '',
      'CARVE: none. If he is helped rather than killed, he gives the CURE — the thing every',
      'demon on this floor is hunting, now carried by the party.',
    ].join('\n'),
    phases: [
      { name: 'The Round', hpThreshold: 'the encounter opens here',
        description: 'He is working. He does not stop to receive them and he denies nothing. The Halo is passive and constant: any Infected condition on a contestant within 3 spaces drops one tier per Clock, including the ones they walked in with. He is curing them while they decide whether to kill him.' },
      { name: 'The Reservoir Answers', hpThreshold: 'on the first attack',
        description: 'He does not retaliate — the reservoir does. Crystal blooms from every surface within 4 spaces, Infected T1 on contact, regrowing each Clock. 19 Crush from a body that is mostly not his any more. He is still talking.' },
      { name: 'Both At Once', hpThreshold: '<=180 total',
        description: 'Halo and Reservoir run together and the street cannot hold both: contestants take Infected and lose Infected in the same Clock, and so does everyone watching. This is the phase where the argument is winnable, because the table can finally SEE the thing he has been saying.' },
      { name: 'The Mask Decides', hpThreshold: '<=70 total, or the Mask destroyed',
        description: 'If the Mask falls, the man underneath is a hundred and seventy years old and dies of it within a Clock, lucid and grateful. If it does not, the Mask stops pretending to be him. A TPK from here is expected and the GM should say so out loud.' },
    ],
  }),

  // ───────── Layer C — Medium Route: the human farm ─────────

  MOB('Royal Guard', {
    part: 'Body',
    color: '#8a7a3a',
    description: 'MEDIUM ROUTE. The crown\'s soldiers. The farm is licensed, the paperwork is in order, and they have read it.',
    notes: [
      '6 Crush, disciplined, in formation, and they do not break when one of them falls.',
      '',
      'GATE: none mechanically — LEGALLY, THEY ARE THE FLOOR. Fighting them is fighting the',
      'capital itself, on camera, with the crown watching (§17). Everything after gets harder.',
      '',
      'CONSEQUENCE OF: the F1 ruling on the Girl, one layer up.',
      '  SHE WAS KILLED → the crown is human, frightened, and has licensed the farm because',
      '    Beelzebub\'s people asked and nobody knows how to say no to them.',
      '  SHE WAS SPARED → the crown is HERS, the guards know what they serve, and the farm',
      '    is a queen\'s concession to a noble she tolerates.',
      'Same statline. Completely different room.',
      '',
      'CARVE: room gather — Orichalcum (their plate).',
    ].join('\n'),
  }),

  ELITE('The Bought Magistrate', {
    color: '#a08a4a',
    description: 'MEDIUM ROUTE. The human official who made the farm legal. He has excellent reasons and he has rehearsed them.',
    bodyParts: [
      { name: 'Head',  maxHp: 9 },
      { name: 'Torso', maxHp: 22 },
      { name: 'Arm L', maxHp: 7 },
      { name: 'Arm R', maxHp: 7 },
      { name: 'Leg L', maxHp: 7 },
      { name: 'Leg R', maxHp: 6 },
    ],
    notes: [
      'GATE — HE DOES NOT FIGHT, HE CALLS. Every Clock he is conscious and able to speak, a',
      'squad of Royal Guards arrives, lawfully, and the party is the one committing a crime.',
      '',
      'WEAK SYSTEM — silence him without killing him. Grapple (§13), Chill to the head,',
      'a hand over a mouth, or simply take him out of earshot. KILLING HIM IS EASIEST AND',
      'WORST: a dead magistrate makes the farm a crime scene the crown must defend, and the',
      'pens are emptied that night, in the way that phrase implies.',
      '',
      'CONSEQUENCE OF: a hundred and seventy years of someone patiently making this normal.',
      'He did not build it. He signed it.',
      '',
      'Attacks: 9 Crush from a bodyguard he never looks at.',
      'CARVE: none. YIELDS: the licence, with a countersignature on it.',
    ].join('\n'),
  }),

  BOSS('Bex, the Petitioner', {
    size: 'Large',
    color: '#7a2a4a',
    description: 'MEDIUM ROUTE FINALE. The man from the burning house. The noble from the desert court. He has been a demon the entire time, and he is very tired of it.',
    bodyParts: [
      { name: 'Head',         maxHp: 20 },
      { name: 'Torso',        maxHp: 55 },
      { name: 'Arm L',        maxHp: 16 },
      { name: 'Arm R',        maxHp: 16 },
      { name: 'Leg L',        maxHp: 17 },
      { name: 'Leg R',        maxHp: 17 },
      { name: 'The Petition', maxHp: 14 },
    ],
    notes: [
      'THE CANON BEAT (Compendium §4.3), read as ONE PERSON: the surviving NPC party leader',
      'runs a human farm, and he — being a demon — wants a specific human sacrifice to cure',
      'his demonic nature. The party sacrifices one, or kills him.',
      '',
      '=== BEX WAS ALWAYS THE RIVAL DEMON ===',
      'FLOOR 1: he leads humans to burn a house with a demon child inside. The party assumed',
      '  he was a man with plot armour. He was a demon killing a rival by proxy.',
      'FLOOR 2: revealed as the Rival Noble — "the demon who helped humans and wants to',
      '  overthrow her". They were sent to assassinate him. THEY MAY HAVE SUCCEEDED. A demon',
      '  is not killed by killing its body, and nobody told them that either.',
      'FLOOR 3: the farm. He has been breeding and buying humans for a hundred and seventy',
      '  years looking for ONE — the specific sacrifice that ends his nature.',
      '',
      'HE HAS FOUND THEM. THE PARTY MEETS THAT PERSON, BY NAME, BEFORE THEY MEET HIM.',
      '',
      'AND HE IS ALSO LOOKING FOR THE LOONG. He knows what its blood does. The sacrifice is',
      'the plan he can reach; the Loong is the plan he cannot. If the party can put the two',
      'of them in a room, the human in his pens stops being necessary — and he will take',
      'that deal instantly, because he never wanted this, he wanted OUT.',
      '',
      'THE FARM IS NOT A RITUAL SITE. It is how the demons of this city eat and go on',
      'existing, and it may be hidden rather than standing in plain sight. The sacrifice is',
      'Bex\'s private hope riding on top of an operation that has other reasons to exist.',
      'That ordering is the encounter. It is not a trolley problem until you have shaken the',
      'trolley\'s hand.',
      '',
      'HE WANTS TO BE HUMAN. He has spent his whole existence pretending to be one, badly,',
      'and manipulating them because it was the only way he knew to be among them. Everything',
      'he did on three floors was this. He is not lying and never has been — the Petition',
      'does not permit it.',
      '',
      'GATE — THE PETITION (14). A formal claim on his own nature. While it is intact he',
      'cannot be killed by anything that is not a refusal, and Torso damage is cosmetic.',
      '',
      'WEAK SYSTEM — three ways out, and they are the whole scene:',
      '  GRANT IT. Hand him the human. He becomes mortal, keeps his word, and the party has',
      '    to carry it. Enormous Exposure (§17). The crowd loves it and nobody else will.',
      '  REFUSE IT. Destroying the Petition (14) makes him killable — properly, this time —',
      '    and makes him a demon forever, which he already knew when he asked.',
      '  ANSWER IT ANOTHER WAY. Nullrot\'s cure and the Loong\'s work on demons. A Medium',
      '    party cannot reach either, but they can KNOW, and knowing is a bargaining chip.',
      '',
      'IF THE GIRL WAS KILLED AT F1: he has spent a century as Beelzebub\'s viceroy without',
      '  ever being told, and the farm is Beelzebub\'s asset. He suspects. He has not asked.',
      'IF THE GIRL WAS SPARED: he lost, she reigns, and the farm is what a defeated rival is',
      '  permitted to keep. He is petitioning out of a position of weakness and knows it.',
      '',
      'Attacks: 12 Bleed, and he apologises for every one of them, exactly as he did at the',
      'house, in the same voice, which is when the table should realise.',
      '',
      'CARVE: none. YIELDS: on a granted petition, a mortal ally in the capital forever.',
    ].join('\n'),
    phases: [
      { name: 'The Foreman', hpThreshold: 'the encounter opens here',
        description: 'He receives them as the man they met on Floor 1 — same manner, same apologies, running a business. He does not pretend not to know them. If the party never worked it out, this is where the voice does it for them.' },
      { name: 'The Asking', hpThreshold: 'on the reveal, or the first attack',
        description: 'He drops the shape and explains, precisely and without threat, what he wants and why it must be that person. He has the paperwork. He will wait while they think, and he will not lie, because the Petition forbids it. Torso cosmetic while it holds.' },
      { name: 'The Pressing', hpThreshold: '<=90 total, on refusal',
        description: '12 Bleed, and he goes for whoever stands between him and the pens rather than whoever is hurting him. A hundred and seventy years of patience ending in about four Moments.' },
      { name: 'Denied', hpThreshold: 'Petition destroyed (14)',
        description: 'Killable at last, and he stops fighting for the human and starts fighting for himself, which he is much worse at. He does not beg. He has been refused before, and he expected this one.' },
    ],
  }),

  // ───────── Layer D — Hard Route: the Loong in hiding ─────────

  MOB('Ashen Inquisitor', {
    part: 'Body',
    color: '#7a5a6a',
    description: 'HARD ROUTE. Demons in plague-doctor masks, going door to door. The city thinks they are help.',
    notes: [
      '6 Bleed, and they work in pairs so one can always leave.',
      '',
      'GATE: KILLING ONE IS FINE. LETTING ONE LEAVE IS NOT. A survivor reports the party\'s',
      'position within a Clock and the search tightens around where they were seen — which',
      'is where the Loong is.',
      '',
      'CONSEQUENCE OF: the desert hunt failing. Same demons, new masks, patient now.',
      '',
      'ALSO: F2\'s HUNT-HOUNDS RETURN AS A TIDE (~25, enemy-scaling S-2), loose in the',
      'streets and still going for the Loong before anything else.',
    ].join('\n'),
  }),

  ELITE('The Cartographer', {
    color: '#8a6a8a',
    description: 'HARD ROUTE. It has never hunted anything. It is drawing a map, and the map is closing.',
    bodyParts: [
      { name: 'Head',  maxHp: 8 },
      { name: 'Torso', maxHp: 19 },
      { name: 'Arm L', maxHp: 6 },
      { name: 'Arm R', maxHp: 6 },
      { name: 'Leg L', maxHp: 6 },
      { name: 'Leg R', maxHp: 6 },
    ],
    notes: [
      'GATE — IT DOES NOT FIGHT AND DOES NOT NEED TO. Every Clock it survives it marks one',
      'more district clear. It is a TIMER wearing a person: let it work four Clocks and it',
      'finds the Loong regardless of what the party does.',
      '',
      'WEAK SYSTEM — the map, not the demon. Burn the map and a century of survey work is',
      'gone. Killing the Cartographer and leaving the map just means the map is inherited.',
      '',
      'CONSEQUENCE OF: a hundred years of the Loong hiding well. Patience was the counter.',
      '',
      'Attacks: 9 Bleed, defensive, purely to be left alone to work.',
      'CARVE: Jade + Inscribed Clay (its instruments).',
    ].join('\n'),
  }),

  BOSS('The One Who Would Be Human', {
    size: 'Large',
    color: '#a03a6a',
    description: 'HARD ROUTE FINALE. It leads the hunt because the Loong is making a cure, and it wants to be cured more than anything has ever wanted anything. NAME IS A PROPOSAL.',
    bodyParts: [
      { name: 'Head',        maxHp: 22 },
      { name: 'Torso',       maxHp: 60 },
      { name: 'Arm L',       maxHp: 18 },
      { name: 'Arm R',       maxHp: 18 },
      { name: 'Leg L',       maxHp: 19 },
      { name: 'Leg R',       maxHp: 19 },
      { name: 'The Wanting', maxHp: 14 },
    ],
    notes: [
      'THE CANON BEAT (Compendium §4.4): the Loong hides in the capital preventing the',
      'disease spreading; demons hunt it as a cure for their nature; the party helps it',
      'develop the cure and protects it.',
      '',
      'IT IS NOT A VILLAIN AND THE PARTY SHOULD STRUGGLE TO TREAT IT AS ONE. LOONG BLOOD',
      'CURES DEMONIC TENDENCIES — that is the cure it is hunting, and it is a real one.',
      'It wants exactly what Bex wants on the other route. The difference is that it will',
      'take the Loong apart to get it, and the Loong is a friend now.',
      '',
      'GATE — THE WANTING (14). It cannot be reasoned with, driven off or repositioned while',
      'the Wanting is intact; every Clock it moves one space closer to the Loong regardless',
      'of what is in the way, and no effect can move it back.',
      '',
      'WEAK SYSTEM — GIVE IT WHAT IT WANTS. The Loong\'s cure works on demons and the Loong',
      'will say so if asked. Offering it ends the fight outright and permanently, and costs',
      'nothing but the thing they came to protect being USED. Destroying the Wanting is the',
      'other answer, and leaves a corpse that died reaching for a cure.',
      '',
      'THERE ARE THREE CURES FOR DEMONIC TENDENCY AND THE HUNT KNOWS ONLY ONE:',
      '  LOONG BLOOD — a solution, and the one it is willing to kill for.',
      '  THE GOD\'S BOON — the table\'s demon god can lift it from his followers if he wills',
      '    it. He is diminished, because BEELZEBUB STOLE HIS POWERS. Revive him and the',
      '    boon returns, and it costs no one anything.',
      '  BEELZEBUB — who can technically do it and does not, because a cured follower is a',
      '    free one. This is the leash Bex is on.',
      'Tell it about the god and the hunt has an alternative for the first time in a',
      'century. Nobody has offered it one.',
      '',
      'CONSEQUENCE OF: the party saving the Loong at F2. It lived, so it built the cure, so',
      'every demon in the world now has a reason to want it opened up.',
      '',
      'Attacks: 12 Crush, and it steps over its own dead to keep moving.',
      '',
      '=== THE LOONG IS HERE BECAUSE THE SOURCE IS HERE ===',
      'Same 300-point block, Warden Form Large / Loong Form Huge, truth-sense intact.',
      'It followed the mask for a hundred and seventy years and it has finally caught up:',
      'NULLROT IS IN THIS CITY. That is why it is not moving, and its presence suppressing',
      'the plague is a side effect the capital has mistaken for a purpose.',
      'So it cannot leave until it has what it came for — which is the F2 escort inverted:',
      'last floor the party moved it to safety, this floor they keep it STILL while',
      'everything comes to it.',
      'If it Turns, the hunt ends instantly and so does the quarantine.',
      '',
      'IT DOES NOT KNOW HOW TO CURE THE PLAGUE AND HAS NEVER CLAIMED TO. Every demon in',
      'the capital believes otherwise, which is the misunderstanding the whole hunt rests on.',
      '',
      'CARVE: none. If it survives and the cure is finished, it sheds a scale (M-5).',
    ].join('\n'),
    phases: [
      { name: 'The Search', hpThreshold: 'the encounter opens here',
        description: 'It has not found the Loong yet. Every Clock it closes one space toward wherever the Loong actually is, and it cannot be misdirected — it is not tracking, it is wanting. The party is fighting a compass.' },
      { name: 'Found', hpThreshold: 'it reaches the Loong, or <=110 total',
        description: '12 Crush, and it goes through contestants rather than around them. It will not target anyone who steps aside, and it says so, which is worse.' },
      { name: 'Reaching', hpThreshold: '<=40 total, or the Wanting destroyed',
        description: 'With the Wanting gone it stops, and asks — for the first time — instead of taking. With the Wanting intact it keeps crawling toward the Loong at 1 space a Moment until something ends it. Either way the table will remember which one they caused.' },
    ],
  }),
];
